export interface BoardTheme {
  id: string;
  name: string;
  /** Which half of the picker the theme belongs in. */
  group: "dark" | "light";
  /** Light square fill. */
  light: string;
  /** Dark square fill. */
  dark: string;
  /** Frame around the board. */
  frame: string;
  /** Page backdrop behind the board. */
  backdrop: string;
  /** Coordinate labels outside the board. */
  label: string;
  /** Surface colour for panels (reserves, HUD). */
  surface: string;
  surfaceText: string;
  /** Fill/stroke for the two piece colours. */
  whitePiece: string;
  whiteOutline: string;
  blackPiece: string;
  blackOutline: string;
  /** Highlight overlays. */
  selected: string;
  lastMove: string;
  target: string;
  accent: string;
}

export const THEMES: BoardTheme[] = [
  {
    id: "wood",
    name: "Classic Wood",
    group: "dark",
    light: "#f2dfc0",
    dark: "#b58863",
    frame: "#6f4a2f",
    backdrop: "#2a1c12",
    label: "#e8d5b7",
    surface: "#3b2718",
    surfaceText: "#f2dfc0",
    whitePiece: "#fdf7ec",
    whiteOutline: "#5a3d28",
    blackPiece: "#2f2118",
    blackOutline: "#0f0a06",
    selected: "#f6c453",
    lastMove: "#d9b25f",
    target: "#3f7d3f",
    accent: "#e0a33c",
  },
  {
    id: "slate",
    name: "Slate Blue",
    group: "dark",
    light: "#e8eef6",
    dark: "#7a93b3",
    frame: "#3d5169",
    backdrop: "#111a26",
    label: "#c7d6e8",
    surface: "#1b2735",
    surfaceText: "#dbe6f4",
    whitePiece: "#ffffff",
    whiteOutline: "#33465c",
    blackPiece: "#22303f",
    blackOutline: "#0a1119",
    selected: "#67b7ff",
    lastMove: "#5b8fc7",
    target: "#2f8f6b",
    accent: "#5aa9ff",
  },
  {
    id: "emerald",
    name: "Emerald",
    group: "dark",
    light: "#edeed1",
    dark: "#779952",
    frame: "#3f5330",
    backdrop: "#16210f",
    label: "#d8e6c2",
    surface: "#22301a",
    surfaceText: "#e6f0d6",
    whitePiece: "#fbfdf3",
    whiteOutline: "#3f5330",
    blackPiece: "#25301c",
    blackOutline: "#0c1207",
    selected: "#f2d24b",
    lastMove: "#cbd35a",
    target: "#2f7f4f",
    accent: "#9ccb5a",
  },
  {
    id: "midnight",
    name: "Midnight",
    group: "dark",
    light: "#5b6472",
    dark: "#2c333d",
    frame: "#191d24",
    backdrop: "#0b0e13",
    label: "#93a0b3",
    surface: "#161b22",
    surfaceText: "#c9d3e0",
    whitePiece: "#f4f7fb",
    whiteOutline: "#2c333d",
    blackPiece: "#131820",
    blackOutline: "#7d8899",
    selected: "#7c9cff",
    lastMove: "#4d5f8f",
    target: "#3fa08a",
    accent: "#8aa4ff",
  },
  {
    id: "coral",
    name: "Coral",
    group: "dark",
    light: "#ffe6dc",
    dark: "#e08672",
    frame: "#a3543f",
    backdrop: "#2d1712",
    label: "#ffd8c9",
    surface: "#3d2019",
    surfaceText: "#ffe6dc",
    whitePiece: "#fff8f4",
    whiteOutline: "#8c4632",
    blackPiece: "#3a1f17",
    blackOutline: "#150a06",
    selected: "#ffc14d",
    lastMove: "#f2a07f",
    target: "#3f8f74",
    accent: "#ff9c72",
  },
  {
    id: "amethyst",
    name: "Amethyst",
    group: "dark",
    light: "#efe7ff",
    dark: "#8f79c4",
    frame: "#503d7a",
    backdrop: "#1a1230",
    label: "#d9cdf5",
    surface: "#251a42",
    surfaceText: "#e9e0ff",
    whitePiece: "#fdfaff",
    whiteOutline: "#4a3a70",
    blackPiece: "#241a3a",
    blackOutline: "#0e0819",
    selected: "#ffd166",
    lastMove: "#b79ce8",
    target: "#3f9a86",
    accent: "#b38dff",
  },
  {
    id: "marble",
    name: "Marble",
    group: "light",
    light: "#f7f6f2",
    dark: "#b6bcc4",
    frame: "#8f959d",
    backdrop: "#e6e4de",
    label: "#3a3d42",
    surface: "#ffffff",
    surfaceText: "#2c2f34",
    whitePiece: "#ffffff",
    whiteOutline: "#6c7178",
    blackPiece: "#3a3d42",
    blackOutline: "#14161a",
    selected: "#f0c14b",
    lastMove: "#dcd08a",
    target: "#5f9e5f",
    accent: "#ba712a",
  },
  {
    id: "sandstone",
    name: "Sandstone",
    group: "light",
    light: "#faeed6",
    dark: "#cfae82",
    frame: "#a8814f",
    backdrop: "#ece0c8",
    label: "#4b3a26",
    surface: "#fff7e8",
    surfaceText: "#3d2f1e",
    whitePiece: "#fffdf7",
    whiteOutline: "#8a6a42",
    blackPiece: "#4a3826",
    blackOutline: "#241a10",
    selected: "#e8a13c",
    lastMove: "#e0c184",
    target: "#5d8f4f",
    accent: "#bb6d27",
  },
  {
    id: "ice",
    name: "Ice",
    group: "light",
    light: "#f0f7fc",
    dark: "#a7c6de",
    frame: "#7396ad",
    backdrop: "#dce9f2",
    label: "#24404f",
    surface: "#ffffff",
    surfaceText: "#1d3644",
    whitePiece: "#ffffff",
    whiteOutline: "#5b7f96",
    blackPiece: "#27404d",
    blackOutline: "#0e1c24",
    selected: "#f2c14e",
    lastMove: "#bcd8ea",
    target: "#4f9c86",
    accent: "#2f7fb0",
  },
  {
    id: "rose",
    name: "Rose",
    group: "dark",
    light: "#f6dfe3",
    dark: "#b3707f",
    frame: "#7d3d4c",
    backdrop: "#2a1218",
    label: "#f0cdd4",
    surface: "#3d1c25",
    surfaceText: "#f8e3e7",
    whitePiece: "#fff6f7",
    whiteOutline: "#7d4351",
    blackPiece: "#31161d",
    blackOutline: "#150609",
    selected: "#f4c15c",
    lastMove: "#d98fa0",
    target: "#4f8f5f",
    accent: "#e0657f",
  },
  {
    id: "forest",
    name: "Forest",
    group: "dark",
    light: "#e4e8cf",
    dark: "#7a8f5c",
    frame: "#4b5c37",
    backdrop: "#141a10",
    label: "#cddab5",
    surface: "#1f2a17",
    surfaceText: "#e6ecd6",
    whitePiece: "#f8fbef",
    whiteOutline: "#4d5c38",
    blackPiece: "#1e2416",
    blackOutline: "#0a0d06",
    selected: "#e8c14e",
    lastMove: "#b6c184",
    target: "#3f8f6a",
    accent: "#8fbf4a",
  },
  {
    id: "mono",
    name: "Mono",
    group: "dark",
    light: "#e8e8e8",
    dark: "#6b6b6b",
    frame: "#2a2a2a",
    backdrop: "#0d0d0d",
    label: "#dcdcdc",
    surface: "#1c1c1c",
    surfaceText: "#f2f2f2",
    whitePiece: "#ffffff",
    whiteOutline: "#000000",
    blackPiece: "#000000",
    blackOutline: "#ffffff",
    selected: "#ffd400",
    lastMove: "#8c8c8c",
    target: "#00b36b",
    accent: "#f2f2f2",
  },
];

export const DEFAULT_THEME_ID = "wood";

export function getTheme(id: string): BoardTheme {
  return THEMES.find((theme) => theme.id === id) ?? THEMES[0];
}
